### ISSUE TITLE
detect InApp Browser

### ISSUE THREAD

**Issue by hikaMaeng** [naver/egjs-agent#10]
Need  additional detecting of popular in-app browsers
* naver app(must!!)
* cacaotalk
* facebook
* facebook messanger
* line

**Comment by happyhj** [comment]
Hi @hikaMaeng!
Currently we are offering `webview` property for inApp browser detection.
Do you need to detect those in-app browsers seperatly?
If you do, let me know by adding comments.

**Comment by VReality64** [comment]
@happyhj 
`webview` property have to give more option than now.
for example, there is a case for applying other function based on in-app browser version like hotfix.
I think it's better eg.Agent give option like plugin to parsing in-app browser version.

when I developing an application on WebView, I temporarily handled app bug in web.
At that time, I had experience developing separated features based on in-app versions.

**Comment by hikaMaeng** [comment]
My Offer is something like
```js
switch(eg.agent().browser.name){
case 'naver_inapp_android':
case 'cacaotalk_inapp_android':
case 'facebook_inapp_android':
...
}
```

**Comment by happyhj** [comment]
@vreality64 
I agree with the requirement to provide the app name and version.

@hikaMaeng 
Your '3rd party plugin system'  looks awesome.
This allows you to extend the agent module without modifying the library source.

I will develop both soon.

Will support the following applications with the bundled parsing rule. It is selected according to the number of users.

* Naver
* Kakao talk
* Line 
* Facebook
* Facebook Messenger
* WhatsApp
* Instagram
* Wechat
* Snapchat

**Comment by happyhj** [comment]
The new API will be look like below. 
Backward compatibility is guaranteed.

```js
// Current Usage
eg.agent(); // -> agentInfo from navigate.userAgent
eg.agent(ua) // -> agentInfo from ua

// Extended Usage
const extendedParseRules = {
    os: [{ 
        criteria: /(myownos)\/([\w\.]+)/i, // <-- optional 
        identity: "my own os",
        versionSearch : "os version" // <-- optional 
    }], browser: [{ 
        criteria: /(myownbrowser)\/([\w\.]+)/i,  // <-- optional 
        identity: "my own browser", 
        versionSearch : "browser version" // <-- optional 
    }]
};

cosnt myAgent = new eg.agent(extendedParseRules) // this will custom agent function
myAgent() // -> agentInfo  from navigate.userAgent
var uaString = 'Mozilla/5.0 myownbrowser/1.3';
myAgent(ua) // -> agentInfo  from navigate.userAgent
```

**Comment by hikaMaeng** [comment]
look so good! thanx f rapid feedback!!

**Comment by ankitch01** [comment]
In Ios, inappbrowser creates iframe. So you can check that if there is an iframe created in your html that means it is an inappbrowser otherwise its a regular mobile browser.

`if(document.getElementById("_cdvIframeBridge")){ 
 alert('its an inappbrowser')}else{ 
 alert('its a mobile browser') 
}`
