### ISSUE TITLE
supports samsung devices

### ISSUE THREAD

**Issue by sculove** [naver/egjs-agent#12]
Mozilla/5.0 (Linux; Tizen 2.3; FamilyHub) AppleWebKit/537.3 (KHTML, like Gecko) Version/2.3 Mobile Safari/537.3
Mozilla/5.0 (Linux; Tizen 3.0; FamilyHub) AppleWebKit/537.3 (KHTML, like Gecko) Version/2.3 Mobile Safari/537.3

**Comment by netil** [comment]
http://developer.samsung.com/technical-doc/view.do?v=T000000203

**Comment by netil** [comment]
Take reference of :
- https://github.com/piwik/device-detector

**Comment by happyhj** [comment]
There is more refs
https://wiki.tizen.org/Tizen_Browser
http://developer.samsung.com/internet/user-agent-string-format

**Comment by happyhj** [comment]
There is no browser name on the user agent string above.
Currently, we are not providing model name like `FamilyHub`.
But we can support detection for **Tizen OS**.
