### ISSUE TITLE
속성값중 webkit,chromium 에 대한 설명을 알고 싶습니다.

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-agent#41]
var browserWebkit = $(".browser > .webkit")[0];
var browserChromium = $(".browser > .chromium")[0];

에서 WEBKIT이 뜻하는 것이 무엇일까요?

크롬 테스트 해보니 FALSE가 나오고 삼성 인터넷 브라우저를 보니 true가 뜨는데 

삼성 인터넷과 크롬 브라우저가 실제 html태그중 동작 하는 것과 하지 않는 것 이있는 것 같아서요.

위의 속성값이 무엇을 뜻하는지 알고 싶습니다.

**Comment by daybrush** [comment]
@changdongchun 

안녕하세요. webkit는 애플사의 브라우저 엔진입니다. 예전 삼성 인터넷 브라우저라면 webkit를 사용했을거고 최근엔 chromium을 사용했을겁니다. 그렇기 때문에 webkit가 true고 chromium이 false일겁니다.
