### ISSUE TITLE
ipad / ios 14버전

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-agent#42]
## Description

iPad에서 os13 이상 인 경우 일부 사용자 들에게 user-agent 에 iPad 문자열이 빠지며 맥북 사용자와 동일한 user-agent 로 표기 되고 있는데 이를 모바일로 인식하기 위해서는 별도 구분값이 있을까요?

**Comment by daybrush** [comment]
@changdongchun 

안녕하세요. iPad OS 13부터 PC 웹 사이트 요청이 기본값입니다.
그렇기 때문에 iPad의 PC 버전 userAgent는 mac의 userAgent와 동일하고 navigator의 속성들도 마찬가지이기 때문에 iPad경우 mac으로 구분됩니다.

mac safari에서는 아직 touch관련이 없기 때문에 iOS를 구분하는 방법은 touch관련 속성이 있는지 확인하는 방법이 있습니다. 

```js
 !!navigator.maxTouchPoints && navigator.maxTouchPoints > 0;
```

**Comment by changdongchun** [comment]
감사합니다.
