### ISSUE TITLE
'uaFullVersion' is being replaced by 'fullVersionList'

### ISSUE THREAD

**Issue by ledgku** [naver/egjs-agent#51]
## Description
안녕하세요.
MDN Client Hints 문서를 보던 중 `Sec-CH-UA-Full-Version`(uaFullVersion)이 Deprecated 된 것을 알게 되었습니다.
문서 내용에 따라 `Sec-CH-UA-Full-Version-List`(fullVersionList)으로 변경이 필요할 것 같습니다.

* 참고한 MDN 문서
  * Sec-CH-UA-Full-Version: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Full-Version
  * Sec-CH-UA-Full-Version-List: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Full-Version-List

**Comment by daybrush** [comment]
@ledgku 
안녕하세요.

참고한 문서와 PR을 확인했습니다.
`fullVersionList` 속성을 확인했고 `getHighEntrophyValues`를 통해 가져오면 brands 속성 대신 사용할 수 있다는 것을 확인했습니다.

더 확인 후  머지하도록 하겠습니다.
감사합니다.

**Comment by daybrush** [comment]
@ledgku 

안녕하세요. PR 보내주신 코드와 내용 반영했고 배포가 됐습니다. 감사합니다.
